// AUTO-GENERATED by scripts/generate-vscode-icon-map.mjs
// Do not edit by hand.

import icon_0 from '$lib/icons/vscode-generated/seti__R.svg';
import icon_1 from '$lib/icons/vscode-generated/seti__argdown.svg';
import icon_2 from '$lib/icons/vscode-generated/seti__asm.svg';
import icon_3 from '$lib/icons/vscode-generated/seti__audio.svg';
import icon_4 from '$lib/icons/vscode-generated/seti__babel.svg';
import icon_5 from '$lib/icons/vscode-generated/seti__bicep.svg';
import icon_6 from '$lib/icons/vscode-generated/seti__bower.svg';
import icon_7 from '$lib/icons/vscode-generated/seti__bsl.svg';
import icon_8 from '$lib/icons/vscode-generated/seti__c-sharp.svg';
import icon_9 from '$lib/icons/vscode-generated/seti__c.svg';
import icon_10 from '$lib/icons/vscode-generated/seti__cake.svg';
import icon_11 from '$lib/icons/vscode-generated/seti__cake_php.svg';
import icon_12 from '$lib/icons/vscode-generated/seti__clock.svg';
import icon_13 from '$lib/icons/vscode-generated/seti__clojure.svg';
import icon_14 from '$lib/icons/vscode-generated/seti__code-climate.svg';
import icon_15 from '$lib/icons/vscode-generated/seti__code-search.svg';
import icon_16 from '$lib/icons/vscode-generated/seti__coffee.svg';
import icon_17 from '$lib/icons/vscode-generated/seti__coldfusion.svg';
import icon_18 from '$lib/icons/vscode-generated/seti__config.svg';
import icon_19 from '$lib/icons/vscode-generated/seti__cpp.svg';
import icon_20 from '$lib/icons/vscode-generated/seti__crystal.svg';
import icon_21 from '$lib/icons/vscode-generated/seti__crystal_embedded.svg';
import icon_22 from '$lib/icons/vscode-generated/seti__css.svg';
import icon_23 from '$lib/icons/vscode-generated/seti__csv.svg';
import icon_24 from '$lib/icons/vscode-generated/seti__cu.svg';
import icon_25 from '$lib/icons/vscode-generated/seti__d.svg';
import icon_26 from '$lib/icons/vscode-generated/seti__dart.svg';
import icon_27 from '$lib/icons/vscode-generated/seti__db.svg';
import icon_28 from '$lib/icons/vscode-generated/seti__default.svg';
import icon_29 from '$lib/icons/vscode-generated/seti__docker.svg';
import icon_30 from '$lib/icons/vscode-generated/seti__ejs.svg';
import icon_31 from '$lib/icons/vscode-generated/seti__elixir.svg';
import icon_32 from '$lib/icons/vscode-generated/seti__elixir_script.svg';
import icon_33 from '$lib/icons/vscode-generated/seti__elm.svg';
import icon_34 from '$lib/icons/vscode-generated/seti__eslint.svg';
import icon_35 from '$lib/icons/vscode-generated/seti__ethereum.svg';
import icon_36 from '$lib/icons/vscode-generated/seti__f-sharp.svg';
import icon_37 from '$lib/icons/vscode-generated/seti__favicon.svg';
import icon_38 from '$lib/icons/vscode-generated/seti__firebase.svg';
import icon_39 from '$lib/icons/vscode-generated/seti__firefox.svg';
import icon_40 from '$lib/icons/vscode-generated/seti__folder.svg';
import icon_41 from '$lib/icons/vscode-generated/seti__font.svg';
import icon_42 from '$lib/icons/vscode-generated/seti__git.svg';
import icon_43 from '$lib/icons/vscode-generated/seti__github.svg';
import icon_44 from '$lib/icons/vscode-generated/seti__go.svg';
import icon_45 from '$lib/icons/vscode-generated/seti__go2.svg';
import icon_46 from '$lib/icons/vscode-generated/seti__godot.svg';
import icon_47 from '$lib/icons/vscode-generated/seti__gradle.svg';
import icon_48 from '$lib/icons/vscode-generated/seti__grails.svg';
import icon_49 from '$lib/icons/vscode-generated/seti__graphql.svg';
import icon_50 from '$lib/icons/vscode-generated/seti__grunt.svg';
import icon_51 from '$lib/icons/vscode-generated/seti__gulp.svg';
import icon_52 from '$lib/icons/vscode-generated/seti__hacklang.svg';
import icon_53 from '$lib/icons/vscode-generated/seti__haml.svg';
import icon_54 from '$lib/icons/vscode-generated/seti__happenings.svg';
import icon_55 from '$lib/icons/vscode-generated/seti__haskell.svg';
import icon_56 from '$lib/icons/vscode-generated/seti__haxe.svg';
import icon_57 from '$lib/icons/vscode-generated/seti__heroku.svg';
import icon_58 from '$lib/icons/vscode-generated/seti__hex.svg';
import icon_59 from '$lib/icons/vscode-generated/seti__html.svg';
import icon_60 from '$lib/icons/vscode-generated/seti__html_erb.svg';
import icon_61 from '$lib/icons/vscode-generated/seti__ignored.svg';
import icon_62 from '$lib/icons/vscode-generated/seti__illustrator.svg';
import icon_63 from '$lib/icons/vscode-generated/seti__image.svg';
import icon_64 from '$lib/icons/vscode-generated/seti__info.svg';
import icon_65 from '$lib/icons/vscode-generated/seti__ionic.svg';
import icon_66 from '$lib/icons/vscode-generated/seti__jade.svg';
import icon_67 from '$lib/icons/vscode-generated/seti__java.svg';
import icon_68 from '$lib/icons/vscode-generated/seti__javascript.svg';
import icon_69 from '$lib/icons/vscode-generated/seti__jenkins.svg';
import icon_70 from '$lib/icons/vscode-generated/seti__jinja.svg';
import icon_71 from '$lib/icons/vscode-generated/seti__json.svg';
import icon_72 from '$lib/icons/vscode-generated/seti__julia.svg';
import icon_73 from '$lib/icons/vscode-generated/seti__karma.svg';
import icon_74 from '$lib/icons/vscode-generated/seti__kotlin.svg';
import icon_75 from '$lib/icons/vscode-generated/seti__less.svg';
import icon_76 from '$lib/icons/vscode-generated/seti__license.svg';
import icon_77 from '$lib/icons/vscode-generated/seti__liquid.svg';
import icon_78 from '$lib/icons/vscode-generated/seti__livescript.svg';
import icon_79 from '$lib/icons/vscode-generated/seti__lock.svg';
import icon_80 from '$lib/icons/vscode-generated/seti__lua.svg';
import icon_81 from '$lib/icons/vscode-generated/seti__makefile.svg';
import icon_82 from '$lib/icons/vscode-generated/seti__markdown.svg';
import icon_83 from '$lib/icons/vscode-generated/seti__maven.svg';
import icon_84 from '$lib/icons/vscode-generated/seti__mdo.svg';
import icon_85 from '$lib/icons/vscode-generated/seti__mustache.svg';
import icon_86 from '$lib/icons/vscode-generated/seti__nim.svg';
import icon_87 from '$lib/icons/vscode-generated/seti__notebook.svg';
import icon_88 from '$lib/icons/vscode-generated/seti__npm.svg';
import icon_89 from '$lib/icons/vscode-generated/seti__npm_ignored.svg';
import icon_90 from '$lib/icons/vscode-generated/seti__nunjucks.svg';
import icon_91 from '$lib/icons/vscode-generated/seti__ocaml.svg';
import icon_92 from '$lib/icons/vscode-generated/seti__odata.svg';
import icon_93 from '$lib/icons/vscode-generated/seti__pddl.svg';
import icon_94 from '$lib/icons/vscode-generated/seti__pdf.svg';
import icon_95 from '$lib/icons/vscode-generated/seti__perl.svg';
import icon_96 from '$lib/icons/vscode-generated/seti__photoshop.svg';
import icon_97 from '$lib/icons/vscode-generated/seti__php.svg';
import icon_98 from '$lib/icons/vscode-generated/seti__pipeline.svg';
import icon_99 from '$lib/icons/vscode-generated/seti__plan.svg';
import icon_100 from '$lib/icons/vscode-generated/seti__platformio.svg';
import icon_101 from '$lib/icons/vscode-generated/seti__powershell.svg';
import icon_102 from '$lib/icons/vscode-generated/seti__prisma.svg';
import icon_103 from '$lib/icons/vscode-generated/seti__prolog.svg';
import icon_104 from '$lib/icons/vscode-generated/seti__pug.svg';
import icon_105 from '$lib/icons/vscode-generated/seti__puppet.svg';
import icon_106 from '$lib/icons/vscode-generated/seti__purescript.svg';
import icon_107 from '$lib/icons/vscode-generated/seti__python.svg';
import icon_108 from '$lib/icons/vscode-generated/seti__react.svg';
import icon_109 from '$lib/icons/vscode-generated/seti__reasonml.svg';
import icon_110 from '$lib/icons/vscode-generated/seti__rescript.svg';
import icon_111 from '$lib/icons/vscode-generated/seti__rollup.svg';
import icon_112 from '$lib/icons/vscode-generated/seti__ruby.svg';
import icon_113 from '$lib/icons/vscode-generated/seti__rust.svg';
import icon_114 from '$lib/icons/vscode-generated/seti__salesforce.svg';
import icon_115 from '$lib/icons/vscode-generated/seti__sass.svg';
import icon_116 from '$lib/icons/vscode-generated/seti__sbt.svg';
import icon_117 from '$lib/icons/vscode-generated/seti__scala.svg';
import icon_118 from '$lib/icons/vscode-generated/seti__shell.svg';
import icon_119 from '$lib/icons/vscode-generated/seti__slim.svg';
import icon_120 from '$lib/icons/vscode-generated/seti__smarty.svg';
import icon_121 from '$lib/icons/vscode-generated/seti__spring.svg';
import icon_122 from '$lib/icons/vscode-generated/seti__stylelint.svg';
import icon_123 from '$lib/icons/vscode-generated/seti__stylus.svg';
import icon_124 from '$lib/icons/vscode-generated/seti__sublime.svg';
import icon_125 from '$lib/icons/vscode-generated/seti__svelte.svg';
import icon_126 from '$lib/icons/vscode-generated/seti__svg.svg';
import icon_127 from '$lib/icons/vscode-generated/seti__swift.svg';
import icon_128 from '$lib/icons/vscode-generated/seti__terraform.svg';
import icon_129 from '$lib/icons/vscode-generated/seti__tex.svg';
import icon_130 from '$lib/icons/vscode-generated/seti__todo.svg';
import icon_131 from '$lib/icons/vscode-generated/seti__tsconfig.svg';
import icon_132 from '$lib/icons/vscode-generated/seti__twig.svg';
import icon_133 from '$lib/icons/vscode-generated/seti__typescript.svg';
import icon_134 from '$lib/icons/vscode-generated/seti__vala.svg';
import icon_135 from '$lib/icons/vscode-generated/seti__video.svg';
import icon_136 from '$lib/icons/vscode-generated/seti__vue.svg';
import icon_137 from '$lib/icons/vscode-generated/seti__wasm.svg';
import icon_138 from '$lib/icons/vscode-generated/seti__wat.svg';
import icon_139 from '$lib/icons/vscode-generated/seti__webpack.svg';
import icon_140 from '$lib/icons/vscode-generated/seti__wgt.svg';
import icon_141 from '$lib/icons/vscode-generated/seti__windows.svg';
import icon_142 from '$lib/icons/vscode-generated/seti__word.svg';
import icon_143 from '$lib/icons/vscode-generated/seti__xls.svg';
import icon_144 from '$lib/icons/vscode-generated/seti__xml.svg';
import icon_145 from '$lib/icons/vscode-generated/seti__yarn.svg';
import icon_146 from '$lib/icons/vscode-generated/seti__yml.svg';
import icon_147 from '$lib/icons/vscode-generated/seti__zip.svg';

import type { IconPackIcons } from '../vscode-icon-map.generated';

const SETI_FILE_NAME_ICONS: Record<string, string> = {
  ".dockerignore": icon_29,
  "babel.config.cjs": icon_4,
  "babel.config.js": icon_4,
  "babel.config.json": icon_4,
  "bower.json": icon_6,
  "changelog": icon_12,
  "changelog.md": icon_12,
  "changes.md": icon_12,
  "cmakelists.txt": icon_81,
  "compiling": icon_76,
  "contributing": icon_76,
  "copying": icon_76,
  "docker-compose.override.yaml": icon_29,
  "docker-compose.override.yml": icon_29,
  "docker-compose.yaml": icon_29,
  "docker-compose.yml": icon_29,
  "docker-healthcheck": icon_29,
  "dockerfile": icon_29,
  "firebase.json": icon_38,
  "folder": icon_40,
  "geckodriver": icon_39,
  "gemfile": icon_112,
  "gruntfile.babel.js": icon_50,
  "gruntfile.coffee": icon_50,
  "gruntfile.js": icon_50,
  "gulpfile": icon_51,
  "gulpfile.js": icon_51,
  "ionic.config.json": icon_65,
  "ionic.project": icon_65,
  "jenkinsfile": icon_69,
  "karma.conf.coffee": icon_73,
  "karma.conf.js": icon_73,
  "licence": icon_76,
  "licence.md": icon_76,
  "license": icon_76,
  "license.md": icon_76,
  "makefile": icon_81,
  "mime.types": icon_18,
  "mix": icon_58,
  "mvnw": icon_83,
  "npm-debug.log": icon_89,
  "omakefile": icon_81,
  "platformio.ini": icon_100,
  "procfile": icon_57,
  "qmakefile": icon_81,
  "readme.md": icon_64,
  "rollup.config.js": icon_111,
  "sass-lint.yml": icon_115,
  "stylelint.config.cjs": icon_122,
  "stylelint.config.js": icon_122,
  "swagger.json": icon_71,
  "swagger.yaml": icon_71,
  "swagger.yml": icon_71,
  "todo": icon_130,
  "tsconfig.json": icon_131,
  "version": icon_12,
  "version.md": icon_12,
  "webpack.common.js": icon_139,
  "webpack.config.build.js": icon_139,
  "webpack.config.js": icon_139,
  "webpack.dev.js": icon_139,
  "webpack.prod.js": icon_139,
  "yarn.clean": icon_145,
  "yarn.lock": icon_145,
};

const SETI_FILE_EXTENSION_ICONS: Record<string, string> = {
  "3dm": icon_126,
  "3ds": icon_126,
  "ad": icon_1,
  "ai": icon_62,
  "apex": icon_114,
  "argdown": icon_1,
  "article": icon_44,
  "asax": icon_59,
  "ascx": icon_59,
  "asm": icon_2,
  "aspx": icon_59,
  "avi": icon_135,
  "babelrc": icon_4,
  "babelrc.cjs": icon_4,
  "babelrc.js": icon_4,
  "bashrc": icon_118,
  "bat": icon_141,
  "bicep": icon_5,
  "bowerrc": icon_6,
  "bsl": icon_7,
  "c": icon_9,
  "c++": icon_19,
  "cake": icon_10,
  "cc": icon_19,
  "cer": icon_79,
  "cert": icon_79,
  "cfc": icon_17,
  "cfg": icon_18,
  "cfm": icon_17,
  "cjsx": icon_108,
  "class": icon_67,
  "classpath": icon_67,
  "clj": icon_13,
  "cljc": icon_13,
  "cljs": icon_13,
  "cls": icon_114,
  "cmd": icon_141,
  "cmx": icon_91,
  "cmxa": icon_91,
  "code-search": icon_15,
  "codeclimate.yml": icon_14,
  "coffee": icon_16,
  "component": icon_59,
  "conf": icon_18,
  "config": icon_18,
  "cpp": icon_19,
  "cr": icon_20,
  "crt": icon_79,
  "cs": icon_8,
  "cshtml": icon_59,
  "cson": icon_71,
  "css": icon_22,
  "css.map": icon_22,
  "csv": icon_23,
  "ctp": icon_11,
  "cu": icon_24,
  "cuh": icon_24,
  "cxx": icon_19,
  "d": icon_25,
  "dae": icon_126,
  "dart": icon_26,
  "direnv": icon_18,
  "doc": icon_142,
  "docx": icon_142,
  "ds_store": icon_61,
  "dtx": icon_129,
  "ecr": icon_21,
  "editorconfig": icon_18,
  "edn": icon_13,
  "ejs": icon_30,
  "elm": icon_33,
  "env": icon_18,
  "eot": icon_41,
  "epp": icon_105,
  "erb": icon_60,
  "erb.html": icon_60,
  "es": icon_68,
  "es5": icon_68,
  "es6": icon_68,
  "es7": icon_68,
  "eslintignore": icon_34,
  "eslintrc": icon_34,
  "eslintrc.cjs": icon_34,
  "eslintrc.js": icon_34,
  "eslintrc.json": icon_34,
  "eslintrc.yaml": icon_34,
  "eslintrc.yml": icon_34,
  "ex": icon_31,
  "exs": icon_32,
  "firebaserc": icon_38,
  "fish": icon_118,
  "flac": icon_3,
  "fs": icon_36,
  "fsx": icon_36,
  "gd": icon_46,
  "gif": icon_63,
  "gitattributes": icon_42,
  "gitconfig": icon_42,
  "github-issues": icon_43,
  "gitignore": icon_42,
  "gitkeep": icon_42,
  "gitmodules": icon_42,
  "go": icon_45,
  "godot": icon_46,
  "gql": icon_49,
  "gradle": icon_47,
  "graphql": icon_49,
  "graphqls": icon_49,
  "groovy": icon_48,
  "gsp": icon_48,
  "h": icon_9,
  "h++": icon_19,
  "hack": icon_52,
  "haml": icon_53,
  "handlebars": icon_85,
  "happenings": icon_54,
  "hbs": icon_85,
  "hh": icon_19,
  "hjs": icon_85,
  "hpp": icon_19,
  "hs": icon_55,
  "htaccess": icon_18,
  "html": icon_59,
  "html.erb": icon_60,
  "hu": icon_24,
  "hx": icon_56,
  "hxml": icon_56,
  "hxp": icon_56,
  "hxs": icon_56,
  "hxx": icon_19,
  "ico": icon_37,
  "ins": icon_129,
  "ipynb": icon_87,
  "jade": icon_66,
  "jar": icon_147,
  "java": icon_67,
  "jinja": icon_70,
  "jinja2": icon_70,
  "jl": icon_72,
  "jpeg": icon_63,
  "jpg": icon_63,
  "js": icon_68,
  "js.map": icon_68,
  "jscsrc": icon_68,
  "jshintrc": icon_68,
  "json": icon_71,
  "jsx": icon_108,
  "key": icon_79,
  "kt": icon_74,
  "kts": icon_74,
  "less": icon_75,
  "lhs": icon_55,
  "liquid": icon_77,
  "litcoffee": icon_16,
  "ls": icon_78,
  "lua": icon_80,
  "m": icon_9,
  "markdown": icon_82,
  "master": icon_59,
  "md": icon_82,
  "mdo": icon_84,
  "ml": icon_91,
  "mli": icon_91,
  "mm": icon_19,
  "mov": icon_135,
  "mp3": icon_3,
  "mp4": icon_135,
  "mpg": icon_135,
  "mustache": icon_85,
  "nim": icon_86,
  "nims": icon_86,
  "nj": icon_90,
  "njk": icon_90,
  "njs": icon_90,
  "npm-debug.log": icon_88,
  "npmignore": icon_88,
  "npmrc": icon_88,
  "nunj": icon_90,
  "nunjs": icon_90,
  "nunjucks": icon_90,
  "obj": icon_126,
  "odata": icon_92,
  "ogg": icon_3,
  "ogv": icon_135,
  "pddl": icon_93,
  "pdf": icon_94,
  "pem": icon_79,
  "php": icon_97,
  "php.inc": icon_97,
  "pipeline": icon_98,
  "pl": icon_95,
  "plan": icon_99,
  "png": icon_63,
  "pp": icon_105,
  "prisma": icon_102,
  "pro": icon_103,
  "properties": icon_67,
  "ps1": icon_101,
  "psd": icon_96,
  "psd1": icon_101,
  "psm1": icon_101,
  "pug": icon_104,
  "purs": icon_106,
  "pxm": icon_63,
  "py": icon_107,
  "r": icon_0,
  "rb": icon_112,
  "re": icon_109,
  "res": icon_110,
  "resi": icon_110,
  "rmd": icon_0,
  "rs": icon_113,
  "s": icon_2,
  "sass": icon_115,
  "sbt": icon_116,
  "scala": icon_117,
  "scss": icon_115,
  "sh": icon_118,
  "slang": icon_21,
  "slide": icon_44,
  "slim": icon_119,
  "slugignore": icon_18,
  "smarty.tpl": icon_120,
  "sol": icon_35,
  "soql": icon_27,
  "spec.js": icon_68,
  "spec.jsx": icon_108,
  "spec.ts": icon_133,
  "spec.tsx": icon_108,
  "springbeans": icon_121,
  "sql": icon_27,
  "sss": icon_22,
  "stache": icon_85,
  "static": icon_18,
  "stl": icon_126,
  "sty": icon_129,
  "styl": icon_123,
  "stylelintignore": icon_122,
  "stylelintrc": icon_122,
  "stylelintrc.js": icon_122,
  "stylelintrc.json": icon_122,
  "stylelintrc.yaml": icon_122,
  "stylelintrc.yml": icon_122,
  "sublime-project": icon_124,
  "sublime-workspace": icon_124,
  "svelte": icon_125,
  "svg": icon_126,
  "svgx": icon_63,
  "swift": icon_127,
  "test.js": icon_68,
  "test.jsx": icon_108,
  "test.ts": icon_133,
  "test.tsx": icon_108,
  "tex": icon_129,
  "tf": icon_128,
  "tf.json": icon_128,
  "tfvars": icon_128,
  "tiff": icon_63,
  "tmp": icon_12,
  "toml": icon_18,
  "tpl": icon_120,
  "tres": icon_46,
  "ts": icon_133,
  "tscn": icon_46,
  "tsx": icon_133,
  "ttf": icon_41,
  "twig": icon_132,
  "txt": icon_28,
  "vala": icon_134,
  "vapi": icon_134,
  "vue": icon_136,
  "wasm": icon_137,
  "wat": icon_138,
  "wav": icon_3,
  "webm": icon_135,
  "webp": icon_63,
  "wgt": icon_140,
  "woff": icon_41,
  "woff2": icon_41,
  "xls": icon_143,
  "xlsx": icon_143,
  "xml": icon_144,
  "yaml": icon_146,
  "yml": icon_146,
  "zip": icon_147,
  "zsh": icon_118,
  "zshrc": icon_118,
};

const SETI_FOLDER_NAME_ICONS: Record<string, string> = {
};

const SETI_FOLDER_NAME_OPEN_ICONS: Record<string, string> = {
};

export const ICON_PACK: IconPackIcons = {
  DEFAULT_FILE_ICON: icon_28,
  DEFAULT_FOLDER_ICON: icon_40,
  DEFAULT_FOLDER_OPEN_ICON: icon_40,
  FILE_NAME_ICONS: SETI_FILE_NAME_ICONS,
  FILE_EXTENSION_ICONS: SETI_FILE_EXTENSION_ICONS,
  FOLDER_NAME_ICONS: SETI_FOLDER_NAME_ICONS,
  FOLDER_NAME_OPEN_ICONS: SETI_FOLDER_NAME_OPEN_ICONS,
};
