// AUTO-GENERATED by scripts/generate-vscode-icon-map.mjs
// Do not edit by hand.

export type IconPack = "material" | "eyecons" | "catppuccin" | "vscode-icons" | "seti";
export const ICON_PACK_IDS = ["material","eyecons","catppuccin","vscode-icons","seti"] as const satisfies readonly IconPack[];
export const DEFAULT_ICON_PACK: IconPack = "eyecons";

export interface IconPackIcons {
  DEFAULT_FILE_ICON: string;
  DEFAULT_FOLDER_ICON: string;
  DEFAULT_FOLDER_OPEN_ICON: string;
  FILE_NAME_ICONS: Record<string, string>;
  FILE_EXTENSION_ICONS: Record<string, string>;
  FOLDER_NAME_ICONS: Record<string, string>;
  FOLDER_NAME_OPEN_ICONS: Record<string, string>;
}

/** Each pack stays an independent Vite chunk. The browser desk loads only
 * the selected pack instead of the native app’s whole multi-pack registry. */
export async function loadIconPack(pack: IconPack): Promise<IconPackIcons> {
  switch (pack) {
    case "material": return (await import('./vscode-icon-packs/material.generated')).ICON_PACK;
    case "eyecons": return (await import('./vscode-icon-packs/eyecons.generated')).ICON_PACK;
    case "catppuccin": return (await import('./vscode-icon-packs/catppuccin.generated')).ICON_PACK;
    case "vscode-icons": return (await import('./vscode-icon-packs/vscode-icons.generated')).ICON_PACK;
    case "seti": return (await import('./vscode-icon-packs/seti.generated')).ICON_PACK;
  }
}

