#!/usr/bin/env node
// Flags comments that probably break the clean-comments rules.
//
// Usage: scan.mjs [--json] [--ci] [--diff-only] [--base <ref>]
//                 [--tracker-prefix <p>] <file>...
//
// Output is TSV: file, line, rule, text. Exit 0 unless --ci is set and a
// high-confidence rule fired.
//
// This is a filter, not a verdict. It finds cheap high-signal patterns so a
// reader can skip the rest of the file; judging whether a comment earns its
// place needs the code around it.

import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
import { syntaxFor, tokenize, commentBody } from './lib.mjs';

const HIGH_CONFIDENCE = new Set([
  'commented-code', 'agent-reference', 'edit-history', 'tracker-reference',
]);

// Tested against the first lines of a comment only: a directive or license
// marker deep inside a long prose comment must not exempt the prose around it.
const DIRECTIVE = new RegExp([
  'eslint-|prettier-|tslint:|biome-ignore|oxlint-|stylelint-|jscpd:',
  '@ts-(ignore|expect-error|nocheck)|type:\\s*ignore|mypy:|pyright:',
  'noqa|pylint:|flake8:|fmt:\\s*(off|on)|isort:|rustfmt::|clippy::',
  'nolint|golangci|go:(build|generate|embed|linkname|noinline)|\\+build',
  'pragma|istanbul ignore|c8 ignore|v8 ignore|codecov|sonar|checkstyle',
  'SuppressWarnings|shellcheck|SPDX-|Copyright|Licensed under|@license',
  '@generated|DO NOT EDIT|coding[:=]|!\\[|eslint\\s|deno-lint',
].join('|'), 'i');

const AGENT = new RegExp([
  "\\bas an ai\\b|\\bas your (ai )?assistant\\b|\\bthis (agent|assistant)\\b",
  "\\bi'?ve\\b|\\bi (have |had |will |just )?(added|updated|changed|removed|fixed|refactored|created|implemented|noticed|think)\\b",
  '\\blet me \\b|\\bper your request\\b|\\bas (you )?requested\\b|\\bas you asked\\b',
  '\\bhope this helps\\b|\\bfeel free to\\b|\\bai[- ]generated\\b',
  '\\bgenerated by (ai|claude|gpt|chatgpt|copilot|cursor|codex)\\b',
  '\\b(claude|chatgpt|copilot|cursor|codex|the model)\\b[^.]{0,40}\\b(added|generated|wrote|created|suggested|suggests)\\b',
].join('|'), 'i');

// A leading past-tense verb is narration in a sentence and a noun phrase in a
// label: "Updated the retry logic so 5xx backs off" vs. "changed files".
const EDIT_HISTORY_VERB =
  /^(added|removed|deleted|changed|updated|refactored|renamed|moved|switched|replaced|migrated|converted)\b/i;

const EDIT_HISTORY = new RegExp([
  '\\bnow (handles|returns|uses|supports)\\b|\\bno longer\\b|\\bused to (be|have|return)\\b',
  '\\bpreviously\\b|\\bper the review\\b|\\baddressing (the )?(review|feedback|comments)\\b',
  '\\bas discussed\\b|\\bas mentioned (above|earlier)\\b',
].join('|'), 'i');

// A comment above a declaration documents it, so the one-line rule does not
// apply. A comment before any code is a file header and does the same job. An
// attribute or decorator line sits between a doc comment and its item and
// counts the same.
const DECLARATION =
  /\b(function|def|fn|func|class|struct|interface|type|enum|const|let|var|public|private|protected|static|async|module|package|pub|trait|impl)\b|^\s*[\w.$]+\s*\(\)\s*\{|^\s*[A-Za-z_$][\w$]*\s*=|^\s*(#\[|@\w)/;

const DIVIDER = /[-=*_]{3,}/;

const CODE_SHAPE = [
  /^(if|for|while|switch|return|import|from|export|const|let|var|def|class|func|fn|public|private|protected|static|package|use|require|elif|else|try|catch|throw|await|async)\b.*[({=:;]/,
  /^[\w.$[\]]+\([^)]*\)\s*[;{]?$/,
  /^[\w.$[\]]+\s*[-+*/]?=[^=]/,
  /^[})\]];?$/,
  /^(#include|#define|@\w+\()/,
];

const STOPWORDS = new Set([
  'the', 'a', 'an', 'this', 'that', 'these', 'to', 'of', 'for', 'and', 'or',
  'is', 'are', 'be', 'it', 'in', 'on', 'with', 'from', 'by', 'we', 'you',
  'method', 'function', 'class', 'constructor', 'helper', 'field', 'property',
  'variable', 'value', 'returns', 'return', 'sets', 'set', 'gets', 'get',
]);

function parseArgs(argv) {
  const opts = { json: false, ci: false, diffOnly: false, base: 'HEAD', prefix: '', files: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--json') opts.json = true;
    else if (a === '--ci') opts.ci = true;
    else if (a === '--diff-only') opts.diffOnly = true;
    else if (a === '--base') opts.base = argv[++i];
    else if (a === '--tracker-prefix') opts.prefix = argv[++i];
    else if (a === '-h' || a === '--help') { usage(); process.exit(0); }
    else if (a.startsWith('-')) { console.error(`clean-comments: unknown option: ${a}`); process.exit(2); }
    else opts.files.push(a);
  }
  return opts;
}

function usage() {
  console.log(fs.readFileSync(new URL(import.meta.url), 'utf8')
    .split('\n').slice(2, 12).map((l) => l.replace(/^\/\/ ?/, '')).join('\n'));
}

// The prefix reaches us from a config file or a flag, so it is data, not a
// pattern.
const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

function beadsPrefix() {
  try {
    const root = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim();
    const cfg = `${root}/.beads/config.yaml`;
    if (fs.existsSync(cfg)) {
      const m = fs.readFileSync(cfg, 'utf8').match(/^\s*issue-prefix:\s*"?([\w-]+)"?/m);
      if (m) return m[1];
    }
    if (fs.existsSync(`${root}/.beads`)) return root.split('/').pop();
  } catch { /* no repo, no tracker */ }
  return '';
}

// 1-based lines the working diff touched. Null means "treat every line as new".
function touchedLines(file, base) {
  try {
    execFileSync('git', ['ls-files', '--error-unmatch', file], { stdio: 'ignore' });
  } catch {
    return null;
  }
  const diff = execFileSync('git', ['diff', '-U0', '--no-color', base, '--', file], { encoding: 'utf8' });
  const set = new Set();
  for (const m of diff.matchAll(/^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@/gm)) {
    const start = Number(m[1]);
    const count = m[2] === undefined ? 1 : Number(m[2]);
    for (let i = 0; i < count; i++) set.add(start + i);
  }
  return set;
}

// Consecutive line comments at the same indent read as one comment.
function group(comments) {
  const out = [];
  for (const c of comments) {
    const prev = out[out.length - 1];
    const shebang = /^#!/.test(c.raw) || (prev && /^#!/.test(prev.raw));
    if (prev && !shebang && c.kind === 'line' && prev.kind === 'line'
      && !!c.doc === !!prev.doc
      && c.startLine === prev.endLine + 1 && c.col === prev.col) {
      prev.endLine = c.endLine;
      prev.raw += '\n' + c.raw;
      prev.lines++;
    } else {
      out.push({ ...c, lines: c.endLine - c.startLine + 1 });
    }
  }
  return out;
}

function identifierWords(codeLine) {
  const m = codeLine.match(
    /\b(?:function|def|fn|func|class|struct|interface|type|enum|const|let|var|public|private|protected|static|async)\s+([A-Za-z_$][\w$]*)/,
  ) ?? codeLine.match(/^\s*([A-Za-z_$][\w$]*)\s*[:=(]/);
  if (!m) return null;
  return m[1]
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[_-]+/g, ' ')
    .toLowerCase()
    .split(/\s+/)
    .filter(Boolean);
}

function detect(g, ctx) {
  const body = commentBody(g);
  if (!body) return null;
  const head = g.raw.split('\n').slice(0, 3).join('\n');
  if (DIRECTIVE.test(head) || /^#!/.test(g.raw)) return null;
  if (body.replace(/[^a-z0-9]/gi, '').length < 3) return null;

  const words = body.split(/\s+/).filter(Boolean);
  const isDoc = g.kind === 'doc' || g.doc === true;
  const next = ctx.codeLines.slice(g.endLine + 1).find((l) => l.trim() !== '');
  const isHeader = !ctx.codeLines.slice(0, g.startLine)
    .some((l) => l.trim() !== '' && !l.startsWith('#!'));
  const documents = isDoc || isHeader || (next ? DECLARATION.test(next) : false);

  // Prose can look like an assignment ("width = height in square mode"), so
  // code shape alone is not enough: real code carries code punctuation.
  if (!isDoc && CODE_SHAPE.some((re) => re.test(body)) && !/[.!?]$/.test(body)
    && /[;(){}[\]'"`]|\d/.test(body)) {
    return { rule: 'commented-code', body };
  }
  if (AGENT.test(body)) return { rule: 'agent-reference', body };
  if (EDIT_HISTORY.test(body) || (EDIT_HISTORY_VERB.test(body) && words.length >= 5)) {
    return { rule: 'edit-history', body };
  }
  if (!/https?:\/\//.test(body)) {
    const jira = body.match(/\b[A-Z][A-Z0-9]{1,9}-\d+\b/);
    const bead = ctx.prefix
      ? body.match(new RegExp(`\\b${escapeRe(ctx.prefix)}-[a-z0-9]+(\\.\\d+)?\\b`, 'i'))
      : null;
    if (jira || bead) return { rule: 'tracker-reference', body };
  }

  const ident = next && !DIVIDER.test(body) ? identifierWords(next) : null;
  if (ident) {
    const said = words.map((w) => w.toLowerCase().replace(/[^\w]/g, ''))
      .filter((w) => w && !STOPWORDS.has(w));
    if (said.length && said.every((w) => ident.includes(w))) {
      return { rule: 'restates-name', body };
    }
  }

  if (!documents) {
    if (g.lines >= 3) return { rule: 'comment-block', body };
    if (words.length > 25) return { rule: 'long-comment', body };
  }
  return null;
}

function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (!opts.files.length) {
    if (process.stdin.isTTY) {
      console.error('clean-comments: no files given and stdin is a terminal.');
      usage();
      process.exit(2);
    }
    opts.files = fs.readFileSync(0, 'utf8').split('\n').map((s) => s.trim()).filter(Boolean);
  }
  const prefix = opts.prefix || beadsPrefix();
  const findings = [];

  for (const file of opts.files) {
    const syn = syntaxFor(file);
    if (!syn) continue;
    let source;
    try { source = fs.readFileSync(file, 'utf8'); } catch { continue; }

    const { comments, codeLines } = tokenize(source, syn);
    const touched = opts.diffOnly ? touchedLines(file, opts.base) : null;

    for (const g of group(comments)) {
      if (opts.diffOnly && touched) {
        let hit = false;
        for (let l = g.startLine; l <= g.endLine && !hit; l++) hit = touched.has(l + 1);
        if (!hit) continue;
      }
      const hit = detect(g, { codeLines, prefix });
      if (hit) findings.push({ file, line: g.startLine + 1, rule: hit.rule, text: hit.body });
    }
  }

  if (opts.json) {
    console.log(JSON.stringify(findings, null, 2));
  } else {
    for (const f of findings) {
      const text = f.text.replace(/\t/g, ' ').slice(0, 160);
      console.log(`${f.file}\t${f.line}\t${f.rule}\t${text}`);
    }
  }

  if (opts.ci && findings.some((f) => HIGH_CONFIDENCE.has(f.rule))) process.exit(1);
}

main();
