/**
 * attn HTML annotation runtime — runs *inside* the document frame.
 *
 * The frame is an opaque-origin sandbox, so the shell cannot touch its DOM.
 * Everything that needs a DOM — selection, geometry, highlight painting,
 * selector resolution — happens here, and results travel to the shell over a
 * private `MessagePort`.
 *
 * This code shares a JavaScript context with the document's own scripts, which
 * are untrusted. It is therefore written to be *unprivileged*: it proposes
 * anchors and reports geometry, and holds no review state worth stealing. The
 * shell treats everything it sends as untrusted input.
 *
 * @see planning/collab/html-annotation.md §1, §3, §5
 */

import type {
  AnchorGeometry,
  AnchorProposal,
  AnchorRenderState,
  AnchorResolution,
  DocMessage,
  DocRect,
  RenderableAnchor,
  ScopeCandidate,
  ShellMessage,
} from '../lib/review/doc-protocol';
import {
  DOC_HELLO,
  DOC_PROTOCOL_VERSION,
  SHELL_INIT,
} from '../lib/review/doc-protocol';
import {
  anchorForElement,
  anchorForRange,
  clampText,
  documentText,
  resolveAnchor,
  textOffsetOf,
} from './selectors';
import { RUNTIME_STYLES } from './styles';

const HIGHLIGHT_BUCKET = 'attn-text';
const HIGHLIGHT_ACTIVE_BUCKET = 'attn-text-active';
/** Context captured either side of a selection, for later disambiguation. */
const CONTEXT_CHARS = 64;

interface LiveAnchor {
  spec: RenderableAnchor;
  range: Range | null;
  element: Element | null;
  status: AnchorResolution['status'];
  confidence: number;
  overlay: HTMLElement | null;
  pin: HTMLElement | null;
}

let port: MessagePort | null = null;
let root: HTMLElement;
let layer: HTMLElement;
/** Hover affordance: the breadcrumb label naming what a click would anchor to. */
let chip: HTMLElement;
let chipBody: HTMLElement;
let selectionPill: HTMLButtonElement;

const anchors = new Map<string, LiveAnchor>();
/** Scope candidates offered in the current hover, keyed by their scopeId. */
const scopeElements = new Map<string, Element>();
/** Innermost element the chip currently names; what a plain click anchors to. */
let hoverTarget: Element | null = null;
/** Scope id of the chip's current segment, so the whole chip is pressable. */
let currentScopeId: string | null = null;
/** Last `mousemove` target, to skip re-resolving the same element every pixel. */
let lastMoveTarget: Element | null = null;
let pendingRange: Range | null = null;
let scopeSeq = 0;
/**
 * Whether a click on the document body commits to a comment.
 *
 * Off until the shell says otherwise. Hover chrome is always live — the point
 * of the redesign is that the annotation model is *visible* — but swallowing
 * every click is only defensible once the document is genuinely under review.
 * An unshared page keeps its links, buttons and form fields working, and the
 * chip is the affordance that still offers to comment.
 */
let inspectEnabled = false;

// ---------------------------------------------------------------------------
// Transport
// ---------------------------------------------------------------------------

function send(message: DocMessage): void {
  port?.postMessage(message);
}

function toDocRect(rect: DOMRect): DocRect {
  return { x: rect.x, y: rect.y, width: rect.width, height: rect.height };
}

/** Merge the many client rects of a multi-line range into per-line bands. */
function rectsOf(target: Range | Element | null): DocRect[] {
  if (!target) return [];
  const list = Array.from(target.getClientRects()).filter(
    (r) => r.width > 0 && r.height > 0,
  );
  return list.slice(0, 128).map(toDocRect);
}

// ---------------------------------------------------------------------------
// Scope chain (validated by planning/collab/prototypes/html-annotation.html)
// ---------------------------------------------------------------------------

/**
 * Structural scopes a comment may anchor to, finest to coarsest.
 *
 * Broader than a prose-block list because the model is now element-first: you
 * point at a thing in the page and comment on *that thing*, so a figure, a
 * button and a section all have to be nameable. Anything outside the set still
 * resolves — {@link fallbackScope} climbs to the nearest laid-out ancestor —
 * so no part of a document is un-commentable.
 */
const SCOPE_TAGS = new Set([
  'TD', 'TH', 'TR', 'LI', 'FIGURE', 'PRE', 'CODE', 'TABLE', 'BLOCKQUOTE',
  'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'P', 'IMG', 'FIGCAPTION', 'UL', 'OL',
  'DL', 'DT', 'DD', 'SECTION', 'ARTICLE', 'ASIDE', 'HEADER', 'FOOTER', 'MAIN',
  'NAV', 'DETAILS', 'SUMMARY', 'FORM', 'VIDEO', 'AUDIO', 'CANVAS', 'SVG',
  'A', 'BUTTON', 'LABEL', 'INPUT', 'TEXTAREA', 'SELECT', 'HR',
]);

const isCell = (el: Element): boolean => el.tagName === 'TD' || el.tagName === 'TH';

/**
 * The nearest ancestor that actually occupies space.
 *
 * Div-soup documents (and anything generated by a layout framework) can nest a
 * hovered node many levels below the closest recognised scope. Falling back to
 * whatever box the cursor is genuinely over keeps every pixel of every document
 * commentable, which is the promise the hover outline makes.
 */
function fallbackScope(el: Element): Element | null {
  let cursor: Element | null = el;
  for (let depth = 0; cursor && cursor !== root && depth < 12; depth += 1) {
    const rect = cursor.getBoundingClientRect();
    if (rect.width > 0 && rect.height > 0) return cursor;
    cursor = cursor.parentElement;
  }
  return null;
}

function candidateChain(el: Element): Element[] {
  const chain: Element[] = [];
  let cursor: Element | null = el;
  while (cursor && cursor !== root && chain.length < 12) {
    // Upper-cased, not compared raw: HTML elements report an upper-case
    // `tagName` but SVG (a different namespace) preserves its case, so an
    // `<svg>` chart silently missed the list and fell through to the fallback.
    if (SCOPE_TAGS.has(cursor.tagName.toUpperCase())) chain.push(cursor);
    cursor = cursor.parentElement;
  }
  if (chain.length === 0) {
    const fallback = fallbackScope(el);
    if (fallback) chain.push(fallback);
  }
  return chain;
}

/**
 * What a plain click anchors to: the innermost thing under the cursor.
 *
 * This is the direct-manipulation contract — you comment on what you pointed
 * at. Coarser scopes stay one click away on the chip's breadcrumb, which is
 * where "actually, the whole row" belongs.
 */
function defaultTarget(chain: Element[]): Element | undefined {
  return chain[0];
}

function rowIndexOf(tr: Element): number {
  const section = tr.parentElement;
  if (!section) return 1;
  return Array.from(section.children).filter((c) => c.tagName === 'TR').indexOf(tr) + 1;
}

function scopeTitle(el: Element): string {
  if (isCell(el)) return 'cell';
  if (el.tagName === 'TR') return el.closest('thead') ? 'header row' : `row ${rowIndexOf(el)}`;
  if (el.tagName === 'LI') return 'list item';
  if (el.tagName === 'PRE') return 'code block';
  if (el.tagName === 'UL' || el.tagName === 'OL') return 'list';
  if (el.tagName === 'A') return 'link';
  if (el.tagName === 'IMG') return 'image';
  if (el.tagName === 'BLOCKQUOTE') return 'quote';
  if (/^H[1-6]$/.test(el.tagName)) return 'heading';
  return el.tagName.toLowerCase();
}

function scopePreview(el: Element): string | null {
  if (el.tagName === 'TR') {
    const cells = Array.from(el.querySelectorAll('th,td')).map((c) => c.textContent?.trim() ?? '');
    const label = el.closest('thead') ? 'header row' : `row ${rowIndexOf(el)}`;
    const rest = [cells[0], cells[1]].filter(Boolean).join(' · ');
    return rest ? `${label} · ${rest}` : label;
  }
  if (isCell(el)) {
    const tr = el.closest('tr');
    const column = tr ? Array.from(tr.children).indexOf(el) : -1;
    const headerRow = el.closest('table')?.querySelector('thead tr');
    const columnName = headerRow?.children[column]?.textContent?.trim();
    const value = el.textContent?.trim() ?? '';
    return columnName ? `${columnName}: ${value}` : value;
  }
  const text = el.textContent?.trim() ?? '';
  return text ? text.slice(0, 80) : null;
}

function commentsOn(el: Element): number {
  let count = 0;
  for (const anchor of anchors.values()) {
    if (anchor.element === el) count += 1;
  }
  return count;
}

// ---------------------------------------------------------------------------
// Proposals
// ---------------------------------------------------------------------------

/**
 * Text immediately before and after *this* range.
 *
 * Derived from the range itself rather than by searching the document for the
 * quote: a search finds the first occurrence, which is the wrong one precisely
 * when the text repeats — the case prefix/suffix exist to disambiguate.
 */
function contextAround(range: Range): { prefix: string; suffix: string } {
  const before = root.ownerDocument.createRange();
  before.selectNodeContents(root);
  before.setEnd(range.startContainer, range.startOffset);

  const after = root.ownerDocument.createRange();
  after.selectNodeContents(root);
  after.setStart(range.endContainer, range.endOffset);

  // Code-unit slices can split a surrogate pair at the cut, leaving a lone
  // half that round-trips as U+FFFD and never matches the document again.
  // Trim to a generous code-unit window first (a spread of the whole document
  // text would be O(doc) per selection), then cut by code points.
  const beforeText = before.toString();
  const prefixCps = [...beforeText.slice(-CONTEXT_CHARS * 2)].slice(-CONTEXT_CHARS);
  const suffixCps = [...after.toString().slice(0, CONTEXT_CHARS * 2)].slice(0, CONTEXT_CHARS);
  if (prefixCps.length > 0 && beforeText.length > CONTEXT_CHARS * 2) {
    // The code-unit pre-cut itself may have split a pair at the window's
    // leading edge; a lone low surrogate there is noise, not context.
    const first = prefixCps[0].charCodeAt(0);
    if (first >= 0xdc00 && first <= 0xdfff) prefixCps.shift();
  }
  return {
    prefix: prefixCps.join(''),
    suffix: suffixCps.join(''),
  };
}

function proposalForRange(range: Range): AnchorProposal {
  const startOffset = textOffsetOf(root, range.startContainer, range.startOffset);
  const endOffset = textOffsetOf(root, range.endContainer, range.endOffset);
  const quote = range.toString();
  const { prefix, suffix } = contextAround(range);
  return {
    html: anchorForRange(root, range),
    // Parser + Rust cap: 4096 BYTES; a character slice overruns it 4× on CJK.
    quote: clampText(quote, 4000, 4096),
    prefix,
    suffix,
    textStart: startOffset,
    textEnd: endOffset,
  };
}

function proposalForElement(el: Element): AnchorProposal {
  const preview = scopePreview(el) ?? scopeTitle(el);
  const html = anchorForElement(root, el, preview);
  const quote = clampText((el.textContent ?? '').trim(), 4000, 4096);
  return {
    html,
    quote,
    prefix: '',
    suffix: '',
    textStart: html.textPosition?.start ?? 0,
    textEnd: html.textPosition?.end ?? 0,
  };
}

// ---------------------------------------------------------------------------
// Text selection
// ---------------------------------------------------------------------------

function selectionIsLive(): boolean {
  const selection = window.getSelection();
  return !!selection && !selection.isCollapsed && selection.rangeCount > 0;
}

function onSelectionChange(): void {
  const selection = window.getSelection();
  if (!selection || selection.isCollapsed || selection.rangeCount === 0) {
    pendingRange = null;
    hideSelectionPill();
    send({ type: 'selectionCleared', v: DOC_PROTOCOL_VERSION });
    return;
  }
  const range = selection.getRangeAt(0);
  if (range.toString().trim().length === 0) return;
  pendingRange = range.cloneRange();
  // A selection competes with element hover for the same pointer; the drag
  // owns the interaction until it is released or cleared.
  hideHover();
  const rects = rectsOf(range);
  const last = rects[rects.length - 1];
  showSelectionPill(last);
  send({
    type: 'selection',
    v: DOC_PROTOCOL_VERSION,
    proposal: proposalForRange(range),
    rects,
    caret: last ?? { x: 0, y: 0, width: 0, height: 0 },
    // Dragging across text is not yet a request to comment on it: the shell
    // must not open a composer — or explain why it cannot — until the person
    // actually asks by pressing the pill.
    explicit: false,
  });
}

function showSelectionPill(near: DocRect | undefined): void {
  if (!near) return;
  selectionPill.style.left = `${near.x + near.width}px`;
  selectionPill.style.top = `${near.y + near.height + 8}px`;
  selectionPill.classList.add('is-visible');
}

function hideSelectionPill(): void {
  selectionPill.classList.remove('is-visible');
}

// ---------------------------------------------------------------------------
// Element inspection: hover outline + breadcrumb chip
//
// The model is the one people already know from element inspectors: point at
// something, see exactly what it is and what a comment would attach to, then
// click. Everything coarser than the thing under the cursor is one hop away on
// the chip's breadcrumb, so "the cell" and "the whole table" are both reachable
// without the cursor ever leaving the region it is pointing at.
// ---------------------------------------------------------------------------

/**
 * How long the chrome survives the cursor being over nothing.
 *
 * Without a grace period, any sliver of unresolvable space between an element
 * and the chip naming it tears the chip down mid-reach.
 */
const HOVER_GRACE_MS = 160;
/** Breadcrumb segments shown; deep trees truncate from the outside in. */
const BREADCRUMB_LIMIT = 4;
/**
 * How far the chip's hit box reaches DOWN over the element it names.
 *
 * The chip sits directly on the element's top edge, so the two boxes are
 * already contiguous and a cursor travelling between them crosses no unclaimed
 * row. This is only slack for sub-pixel rounding — and it is deliberately tiny,
 * because every pixel of it is a pixel of the element that answers to the chip
 * instead of to the document.
 */
const CHIP_OVERLAP = 2;

let hideTimer = 0;

/** Is this node part of the runtime's own UI rather than the document's? */
function isChrome(node: EventTarget | null): boolean {
  return node instanceof Node && layer.contains(node);
}

function cancelHide(): void {
  if (!hideTimer) return;
  clearTimeout(hideTimer);
  hideTimer = 0;
}

function scheduleHide(): void {
  if (hideTimer) return;
  hideTimer = setTimeout(() => {
    hideTimer = 0;
    hideHover();
  }, HOVER_GRACE_MS) as unknown as number;
}

function onPointerMove(event: MouseEvent): void {
  // A document that cannot take a comment gets no hover chrome at all. The
  // chip is opaque and clickable and is painted OVER the page, so showing it on
  // a document that is merely being read would occlude — and swallow clicks on
  // — a live page's own links, to offer an affordance that could only ever
  // answer "share this first". The selection pill remains the way to ask.
  if (!inspectEnabled) return;
  // THE SELF-HIDE BUG (attn-yqun.2): the runtime's own chrome is part of the
  // document it is annotating, so a cursor moving onto the chip is a mousemove
  // whose target resolves to no document scope. Treating that as "hovering
  // nothing" hid the chip out from under the cursor reaching for it, which made
  // it structurally unclickable. Chrome is never a hover subject.
  if (chip.contains(event.target as Node)) {
    cancelHide();
    return;
  }
  // Other chrome — a committed comment's pin, the selection pill — is not the
  // chip and must NOT hold it open: those hang outside the elements they belong
  // to, so resting on one used to cancel a pending hide that nothing re-armed,
  // stranding the chip on an element the cursor had long since left.
  if (isChrome(event.target)) return;
  // An active text selection owns the interaction; the two gestures must never
  // compete for the same drag.
  if (selectionIsLive()) {
    hideHover();
    return;
  }
  const target = event.target;
  if (!(target instanceof Element)) return;
  if (target === lastMoveTarget) {
    // Not a pure no-op: leaving the chip arms a hide, and the cursor may have
    // done nothing worse than clip the chip on its way back to the element it
    // was already on. Returning without disarming would time the chip out from
    // under a stationary cursor.
    if (hoverTarget) cancelHide();
    return;
  }
  lastMoveTarget = target;

  const chain = candidateChain(target);
  const block = defaultTarget(chain);
  if (!block) {
    scheduleHide();
    return;
  }
  cancelHide();
  if (block === hoverTarget) return;
  hoverTarget = block;
  outline(block);
  renderChip(publishScopeHover(chain));
}

function hideHover(): void {
  cancelHide();
  hoverTarget = null;
  lastMoveTarget = null;
  chip.classList.remove('is-visible');
  outline(undefined);
}

/**
 * Commit to the element the chip currently names.
 *
 * You comment on what the chip says you are commenting on — nothing else. That
 * is not a nicety, it is the safety rail: re-deriving a scope from the click
 * target instead let a click commit to an element that was never outlined or
 * named. The reachable case was mundane — drag-select a sentence to read it,
 * then click elsewhere to dismiss the selection. The chrome was hidden for the
 * whole gesture (a live selection suppresses it), yet by click time mousedown
 * had already collapsed the selection, so the guard here saw nothing and a
 * composer opened on whatever happened to be under the pointer.
 *
 * Requiring a visible chip also means a click can only ever be swallowed while
 * the person can SEE what it will attach to.
 */
function onDocumentClick(event: MouseEvent): void {
  if (isChrome(event.target)) return;
  if (!inspectEnabled) return;
  const target = event.target;
  if (!(target instanceof Element)) return;
  const scopeId = currentScopeId;
  const named = hoverTarget;
  // No chip on screen (hidden by a selection, timed out, never raised) means
  // nothing was offered, so nothing is taken: the click belongs to the page.
  if (!scopeId || !named) return;
  // The click must land on the very thing the chip names. A pin or overlay can
  // sit over a neighbour, and the pointer can outrun the hover.
  if (named !== target && !named.contains(target)) return;
  event.preventDefault();
  event.stopPropagation();
  pickScope(scopeId);
}

function publishScopeHover(chain: Element[]): ScopeCandidate[] {
  scopeElements.clear();
  const candidates: ScopeCandidate[] = chain.slice(0, 8).map((el) => {
    const scopeId = `scope-${(scopeSeq += 1)}`;
    scopeElements.set(scopeId, el);
    const preview = scopePreview(el);
    return {
      scopeId,
      title: scopeTitle(el),
      // The row/cell branches assemble from full cell text; the parser drops
      // any candidate whose preview exceeds 256 BYTES, so bound at the wire.
      preview: preview === null ? null : clampText(preview, 200, 256),
      selector: anchorForElement(root, el, '').cssSelector,
      commentCount: commentsOn(el),
      rects: rectsOf(el),
    };
  });
  send({ type: 'scopeHover', v: DOC_PROTOCOL_VERSION, chain: candidates });
  return candidates;
}

/**
 * Render the label for the current hover: `table › row 2 › cell`.
 *
 * Outermost first so the breadcrumb reads the way a path does, with the thing
 * actually under the cursor last and marked current.
 */
function renderChip(candidates: ScopeCandidate[]): void {
  chipBody.textContent = '';
  currentScopeId = candidates[0]?.scopeId ?? null;
  if (candidates.length === 0) {
    chip.classList.remove('is-visible');
    return;
  }
  // `candidates` is innermost-first (the wire order the shell expects); the
  // breadcrumb reads the other way.
  const shown = candidates.slice(0, BREADCRUMB_LIMIT).reverse();
  const truncated = candidates.length > BREADCRUMB_LIMIT;
  if (truncated) {
    const ellipsis = document.createElement('span');
    ellipsis.className = 'attn-chip-sep';
    ellipsis.textContent = '…';
    chipBody.appendChild(ellipsis);
  }
  shown.forEach((candidate, index) => {
    if (index > 0 || truncated) {
      const separator = document.createElement('span');
      separator.className = 'attn-chip-sep';
      separator.textContent = '›';
      separator.setAttribute('aria-hidden', 'true');
      chipBody.appendChild(separator);
    }
    const current = index === shown.length - 1;
    const segment = document.createElement('button');
    segment.type = 'button';
    segment.className = 'attn-chip-seg';
    if (current) segment.classList.add('is-current');
    segment.dataset.scope = candidate.scopeId;
    segment.setAttribute(
      'aria-label',
      `Comment on ${candidate.preview ?? candidate.title}`,
    );

    const title = document.createElement('span');
    title.className = 'attn-chip-title';
    title.textContent = candidate.title;
    segment.appendChild(title);

    // Only the current segment carries content: the breadcrumb is for aiming,
    // and repeating every ancestor's text would bury the thing being named.
    if (current && candidate.preview && candidate.preview !== candidate.title) {
      const preview = document.createElement('span');
      preview.className = 'attn-chip-preview';
      preview.textContent = clampText(candidate.preview, 48, 192);
      segment.appendChild(preview);
    }
    if (candidate.commentCount > 0) {
      const badge = document.createElement('span');
      badge.className = 'attn-chip-count';
      badge.textContent = String(candidate.commentCount);
      segment.appendChild(badge);
    }

    segment.addEventListener('mouseenter', () => outline(scopeElements.get(candidate.scopeId)));
    segment.addEventListener('mouseleave', () => outline(hoverTarget ?? undefined));
    // Same reason the selection pill does it: a mousedown here would collapse
    // any live selection and can begin one in the document underneath, so the
    // press must not reach the page at all — only the click that follows it
    // means anything.
    segment.addEventListener('mousedown', (event) => event.preventDefault());
    segment.addEventListener('click', (event) => {
      event.preventDefault();
      event.stopPropagation();
      pickScope(candidate.scopeId);
    });
    chipBody.appendChild(segment);
  });

  chip.classList.add('is-visible');
  if (hoverTarget) positionChip(hoverTarget);
}

function positionChip(el: Element): void {
  const rect = el.getBoundingClientRect();
  const top = rect.top + window.scrollY;
  const left = rect.left + window.scrollX;
  // Measured, not assumed: the chip's height depends on the host document's
  // font metrics, and a stale guess would leave the gap this positioning
  // exists to close.
  const height = chip.offsetHeight;
  // The chip's hit box overlaps the element's top edge (see the transparent
  // bottom padding in RUNTIME_STYLES) so a cursor travelling from the element
  // to the chip never crosses unclaimed space. Documents that start at the very
  // top have nowhere above to put it, so it tucks just inside instead.
  const above = top - height + CHIP_OVERLAP;
  chip.style.top = `${above < window.scrollY ? top : above}px`;
  // Clamped at BOTH edges. The layer is absolutely positioned in the document,
  // so a chip overhanging the right edge widens `scrollWidth` and raises a
  // horizontal scrollbar on a document that never had one — hovering the last
  // cell of a wide table was enough.
  const widest = document.documentElement.clientWidth - chip.offsetWidth - 2;
  chip.style.left = `${Math.max(Math.min(left, window.scrollX + Math.max(widest, 0)), 2)}px`;
}

let outlineEl: HTMLElement | null = null;

function outline(el: Element | undefined): void {
  if (!el) {
    outlineEl?.remove();
    outlineEl = null;
    return;
  }
  const rect = el.getBoundingClientRect();
  const box = outlineEl ?? document.createElement('div');
  box.className = 'attn-outline';
  box.style.cssText = `top:${rect.top + window.scrollY}px;left:${rect.left + window.scrollX}px;width:${rect.width}px;height:${rect.height}px`;
  if (!outlineEl) layer.appendChild(box);
  outlineEl = box;
}

function pickScope(scopeId: string): void {
  const el = scopeElements.get(scopeId);
  if (!el) return;
  hideHover();
  send({
    type: 'scopePicked',
    v: DOC_PROTOCOL_VERSION,
    proposal: proposalForElement(el),
    rects: rectsOf(el),
    // Picking a scope is only ever a deliberate act — a chip press, a click in
    // inspect mode, or the shell replaying one. The shell owes an answer.
    explicit: true,
  });
}

// ---------------------------------------------------------------------------
// Painting anchors
// ---------------------------------------------------------------------------

/**
 * Text highlights use the CSS Custom Highlight API, so no wrapper spans are
 * injected — the document's own DOM is never mutated by a highlight, which
 * keeps its scripts and our selectors from fighting over the tree.
 */
function repaintHighlights(): void {
  const highlights = (CSS as unknown as { highlights?: Map<string, unknown> }).highlights;
  if (!highlights || typeof Highlight === 'undefined') return;
  const base: Range[] = [];
  const active: Range[] = [];
  for (const anchor of anchors.values()) {
    if (anchor.spec.html.target !== 'text_range' || !anchor.range) continue;
    (anchor.spec.state === 'active' ? active : base).push(anchor.range);
  }
  highlights.set(HIGHLIGHT_BUCKET, new Highlight(...base));
  highlights.set(HIGHLIGHT_ACTIVE_BUCKET, new Highlight(...active));
}

/**
 * Element anchors get an overlay whose fill is `pointer-events: none`, so the
 * user can still select — and comment on — the text underneath. Only the small
 * pin and count chip are interactive.
 */
function paintElementAnchor(anchor: LiveAnchor): void {
  anchor.overlay?.remove();
  anchor.pin?.remove();
  anchor.overlay = null;
  anchor.pin = null;
  if (anchor.spec.html.target !== 'element' || !anchor.element) return;

  const rect = anchor.element.getBoundingClientRect();
  const top = rect.top + window.scrollY;
  const left = rect.left + window.scrollX;

  const overlay = document.createElement('div');
  overlay.className = 'attn-overlay';
  overlay.dataset.state = anchor.spec.state;
  overlay.style.cssText = `top:${top}px;left:${left}px;width:${rect.width}px;height:${rect.height}px`;
  layer.appendChild(overlay);
  anchor.overlay = overlay;

  // Persistent marker: a committed comment stays visible without hovering, so
  // the document reads as annotated at a glance.
  const pin = document.createElement('button');
  pin.type = 'button';
  pin.className = 'attn-pin';
  pin.dataset.state = anchor.spec.state;
  pin.textContent = anchor.spec.label ?? '1';
  pin.style.cssText = `top:${top - 10}px;left:${left - 14}px`;
  pin.addEventListener('click', (event) => {
    event.stopPropagation();
    send({
      type: 'anchorActivated',
      v: DOC_PROTOCOL_VERSION,
      anchorId: anchor.spec.anchorId,
    });
  });
  layer.appendChild(pin);
  anchor.pin = pin;
}

function resolveAndPaint(spec: RenderableAnchor): LiveAnchor {
  const resolution = resolveAnchor(root, {
    anchor: spec.html,
    quote: spec.quote,
    prefix: spec.prefix,
    suffix: spec.suffix,
  });
  const anchor: LiveAnchor = {
    spec,
    range: resolution.range,
    element: resolution.element,
    status: resolution.status,
    confidence: resolution.confidence,
    overlay: null,
    pin: null,
  };
  paintElementAnchor(anchor);
  return anchor;
}

function renderAnchors(specs: RenderableAnchor[]): void {
  for (const anchor of anchors.values()) {
    anchor.overlay?.remove();
    anchor.pin?.remove();
  }
  anchors.clear();
  for (const spec of specs) {
    anchors.set(spec.anchorId, resolveAndPaint(spec));
  }
  repaintHighlights();
  publishResolutions();
}

function publishResolutions(): void {
  const results: AnchorResolution[] = [];
  for (const anchor of anchors.values()) {
    results.push({
      anchorId: anchor.spec.anchorId,
      status: anchor.status,
      confidence: anchor.confidence,
      rects: rectsOf(anchor.range ?? anchor.element),
    });
  }
  send({ type: 'anchorsResolved', v: DOC_PROTOCOL_VERSION, results });
}

function publishGeometry(): void {
  const results: AnchorGeometry[] = [];
  for (const anchor of anchors.values()) {
    results.push({
      anchorId: anchor.spec.anchorId,
      rects: rectsOf(anchor.range ?? anchor.element),
    });
  }
  send({
    type: 'geometry',
    v: DOC_PROTOCOL_VERSION,
    results,
    scrollTop: window.scrollY,
  });
}

function setAnchorState(anchorId: string, state: AnchorRenderState): void {
  const anchor = anchors.get(anchorId);
  if (!anchor) return;
  anchor.spec = { ...anchor.spec, state };
  if (anchor.overlay) anchor.overlay.dataset.state = state;
  if (anchor.pin) anchor.pin.dataset.state = state;
  repaintHighlights();
}

function focusAnchor(anchorId: string, scrollIntoView: boolean): void {
  const anchor = anchors.get(anchorId);
  if (!anchor || !scrollIntoView) return;
  const target = anchor.element ?? anchor.range?.startContainer.parentElement;
  target?.scrollIntoView({ behavior: 'smooth', block: 'center' });
}

// ---------------------------------------------------------------------------
// Reflow
// ---------------------------------------------------------------------------

let frame = 0;

/**
 * Rects are reported in the frame's own viewport coordinates and the shell
 * cannot observe this frame's scroll cross-origin, so every reflow has to be
 * pushed. Coalesced to one animation frame so a smooth scroll does not become
 * a message storm.
 */
function scheduleReflow(): void {
  if (frame) return;
  frame = requestAnimationFrame(() => {
    frame = 0;
    for (const anchor of anchors.values()) paintElementAnchor(anchor);
    // The hover chrome is positioned in document coordinates, so it rides a
    // scroll for free — but a reflow moves the element out from under it, and a
    // chip pointing at the wrong thing is worse than no chip. A document script
    // may also have removed that element outright, whose rects are all zero —
    // parking the outline and chip in the top-left corner of the page.
    if (hoverTarget && !hoverTarget.isConnected) {
      hideHover();
    } else if (hoverTarget) {
      outline(hoverTarget);
      positionChip(hoverTarget);
    }
    repaintHighlights();
    publishGeometry();
  });
}

// ---------------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------------

function handleShellMessage(message: ShellMessage): void {
  switch (message.type) {
    case 'renderAnchors':
      renderAnchors(message.anchors);
      break;
    case 'setAnchorState':
      setAnchorState(message.anchorId, message.state);
      break;
    case 'focusAnchor':
      focusAnchor(message.anchorId, message.scrollIntoView);
      break;
    case 'pickScope':
      pickScope(message.scopeId);
      break;
    case 'dismissSelection':
      window.getSelection()?.removeAllRanges();
      pendingRange = null;
      hideSelectionPill();
      break;
    case 'inspect': {
      const enabled = message.enabled === true;
      // Turning inspection off has to take DOWN the chrome already on screen,
      // not merely stop raising more. A stopped or revoked room leaves a
      // visible chip whose own click handler bypasses `onDocumentClick` — so it
      // would go on swallowing page clicks and emitting proposals for a
      // document that is no longer reviewable.
      if (inspectEnabled && !enabled) {
        hideHover();
        currentScopeId = null;
      }
      inspectEnabled = enabled;
      break;
    }
    case 'theme':
      root.dataset.attnTheme = message.mode;
      break;
    default:
      break;
  }
}

function mountChrome(): void {
  const style = document.createElement('style');
  style.textContent = RUNTIME_STYLES;
  document.head.appendChild(style);

  layer = document.createElement('div');
  layer.className = 'attn-layer';
  document.body.appendChild(layer);

  chip = document.createElement('div');
  chip.className = 'attn-chip';
  chip.setAttribute('role', 'toolbar');
  chip.setAttribute('aria-label', 'Comment on this element');
  // Entering the chip is the one gesture the grace period exists to protect.
  chip.addEventListener('mouseenter', cancelHide);
  chip.addEventListener('mouseleave', scheduleHide);
  // The whole chip is pressable, not just its segments. Its reach corridor and
  // its padding sit ON TOP of the document, so a click there can never fall
  // through to the page — leaving a strip that did nothing at all: no comment,
  // no page interaction. A press anywhere on a label that names something means
  // "comment on that thing".
  chip.addEventListener('mousedown', (event) => event.preventDefault());
  chip.addEventListener('click', (event) => {
    const target = event.target;
    // Segments carry their own scope and handle themselves.
    if (target instanceof Element && target.closest('.attn-chip-seg')) return;
    event.preventDefault();
    event.stopPropagation();
    if (currentScopeId) pickScope(currentScopeId);
  });
  chipBody = document.createElement('div');
  chipBody.className = 'attn-chip-body';
  chip.appendChild(chipBody);
  layer.appendChild(chip);

  selectionPill = document.createElement('button');
  selectionPill.type = 'button';
  selectionPill.className = 'attn-pill';
  selectionPill.textContent = 'Comment';
  // mousedown would collapse the selection before the click lands.
  selectionPill.addEventListener('mousedown', (event) => event.preventDefault());
  selectionPill.addEventListener('click', (event) => {
    event.preventDefault();
    event.stopPropagation();
    if (!pendingRange) return;
    const rects = rectsOf(pendingRange);
    send({
      type: 'selection',
      v: DOC_PROTOCOL_VERSION,
      proposal: proposalForRange(pendingRange),
      rects,
      caret: rects[rects.length - 1] ?? { x: 0, y: 0, width: 0, height: 0 },
      // The person asked. Whatever the shell decides, it must say so.
      explicit: true,
    });
  });
  layer.appendChild(selectionPill);
}

function attachPort(candidate: MessagePort): void {
  port = candidate;
  port.onmessage = (event: MessageEvent) => {
    // The port is private, but the document's own scripts share this context
    // and could reach it, so shape is still checked before use.
    const data = event.data as ShellMessage | undefined;
    if (!data || typeof data !== 'object' || typeof data.type !== 'string') return;
    if (data.v !== DOC_PROTOCOL_VERSION) return;
    handleShellMessage(data);
  };
  port.start();

  send({
    type: 'ready',
    v: DOC_PROTOCOL_VERSION,
    textLength: documentText(root).length,
    title: clampText(document.title, 200, 512),
  });
}

function boot(): void {
  // A document saved after injection ("Save page as…" of a reviewed doc,
  // then re-shared) already carries a copy of this runtime. Two instances
  // would both answer the handshake and fight over the port — the loser's
  // empty geometry reports would flap the shell's rail every scroll. Both
  // copies share this window, so a global is a reliable mutex.
  const guard = window as Window & { __attnDocRuntime?: boolean };
  if (guard.__attnDocRuntime) return;
  guard.__attnDocRuntime = true;

  root = document.body;
  mountChrome();

  document.addEventListener('selectionchange', onSelectionChange);
  document.addEventListener('mousemove', onPointerMove, { passive: true });
  // Capture phase: in inspect mode the click has to be taken before any of the
  // document's own handlers see it, or a link navigates the frame away from the
  // thing the person was commenting on. Not passive — it calls preventDefault.
  document.addEventListener('click', onDocumentClick, true);
  // Leaving the document entirely is unambiguous; no grace period needed.
  document.documentElement.addEventListener('mouseleave', hideHover);
  window.addEventListener('scroll', scheduleReflow, { passive: true });
  window.addEventListener('resize', scheduleReflow, { passive: true });
  new ResizeObserver(scheduleReflow).observe(document.body);

  window.addEventListener('message', (event: MessageEvent) => {
    // Origin is always "null" for an opaque frame, so it carries no information.
    // The shell is identified by being our parent; the port it hands over is
    // what makes every later message trustworthy.
    if (event.source !== window.parent) return;
    const data = event.data as { type?: unknown } | undefined;
    if (!data || data.type !== SHELL_INIT) return;
    const [candidate] = event.ports;
    if (candidate) attachPort(candidate);
  });

  window.parent.postMessage({ type: DOC_HELLO, v: DOC_PROTOCOL_VERSION }, '*');
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', boot, { once: true });
} else {
  boot();
}
